// Mocks generated by Mockito 5.4.5 from annotations
// in committee_app/test/screens/host/host_dashboard_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i13;

import 'package:committee_app/core/models/committee.dart' as _i7;
import 'package:committee_app/core/models/member.dart' as _i8;
import 'package:committee_app/core/models/payment.dart' as _i9;
import 'package:committee_app/features/auth/data/auth_service.dart' as _i4;
import 'package:committee_app/services/auto_sync_service.dart' as _i11;
import 'package:committee_app/services/database_service.dart' as _i6;
import 'package:committee_app/services/realtime_sync_service.dart' as _i12;
import 'package:committee_app/services/sync_service.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSyncResult_0 extends _i1.SmartFake implements _i2.SyncResult {
  _FakeSyncResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncCounts_1 extends _i1.SmartFake implements _i2.SyncCounts {
  _FakeSyncCounts_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserMetadata_2 extends _i1.SmartFake implements _i3.UserMetadata {
  _FakeUserMetadata_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiFactor_3 extends _i1.SmartFake implements _i3.MultiFactor {
  _FakeMultiFactor_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIdTokenResult_4 extends _i1.SmartFake implements _i3.IdTokenResult {
  _FakeIdTokenResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCredential_5 extends _i1.SmartFake
    implements _i3.UserCredential {
  _FakeUserCredential_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfirmationResult_6 extends _i1.SmartFake
    implements _i3.ConfirmationResult {
  _FakeConfirmationResult_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_7 extends _i1.SmartFake implements _i3.User {
  _FakeUser_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i3.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i5.Stream<_i3.User?>.empty(),
      ) as _i5.Stream<_i3.User?>);

  @override
  bool get isEmailVerified => (super.noSuchMethod(
        Invocation.getter(#isEmailVerified),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i3.UserCredential?> signUp({
    required String? email,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i5.Future<_i3.UserCredential?>.value(),
      ) as _i5.Future<_i3.UserCredential?>);

  @override
  _i5.Future<_i3.UserCredential?> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i3.UserCredential?>.value(),
      ) as _i5.Future<_i3.UserCredential?>);

  @override
  _i5.Future<_i3.UserCredential?> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue: _i5.Future<_i3.UserCredential?>.value(),
      ) as _i5.Future<_i3.UserCredential?>);

  @override
  _i5.Future<_i3.UserCredential?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<_i3.UserCredential?>.value(),
      ) as _i5.Future<_i3.UserCredential?>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> reloadUser() => (super.noSuchMethod(
        Invocation.method(
          #reloadUser,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i6.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveCommittee(_i7.Committee? committee) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCommittee,
          [committee],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i7.Committee> getHostedCommittees(String? hostId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHostedCommittees,
          [hostId],
        ),
        returnValue: <_i7.Committee>[],
      ) as List<_i7.Committee>);

  @override
  _i7.Committee? getCommitteeById(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getCommitteeById,
        [id],
      )) as _i7.Committee?);

  @override
  _i7.Committee? getCommitteeByCode(String? code) =>
      (super.noSuchMethod(Invocation.method(
        #getCommitteeByCode,
        [code],
      )) as _i7.Committee?);

  @override
  _i5.Future<void> deleteCommittee(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCommittee,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveMember(_i8.Member? member) => (super.noSuchMethod(
        Invocation.method(
          #saveMember,
          [member],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i8.Member> getMembersByCommittee(String? committeeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMembersByCommittee,
          [committeeId],
        ),
        returnValue: <_i8.Member>[],
      ) as List<_i8.Member>);

  @override
  _i8.Member? getMemberById(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getMemberById,
        [id],
      )) as _i8.Member?);

  @override
  _i8.Member? getMemberByCode(
    String? committeeId,
    String? memberCode,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getMemberByCode,
        [
          committeeId,
          memberCode,
        ],
      )) as _i8.Member?);

  @override
  _i5.Future<void> deleteMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMember,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateMemberPayoutOrder(
    String? memberId,
    int? order,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberPayoutOrder,
          [
            memberId,
            order,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> savePayment(_i9.Payment? payment) => (super.noSuchMethod(
        Invocation.method(
          #savePayment,
          [payment],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i9.Payment> getPaymentsByCommittee(String? committeeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsByCommittee,
          [committeeId],
        ),
        returnValue: <_i9.Payment>[],
      ) as List<_i9.Payment>);

  @override
  List<_i9.Payment> getPaymentsByMember(String? memberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsByMember,
          [memberId],
        ),
        returnValue: <_i9.Payment>[],
      ) as List<_i9.Payment>);

  @override
  _i9.Payment? getPayment(
    String? memberId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getPayment,
        [
          memberId,
          date,
        ],
      )) as _i9.Payment?);

  @override
  _i5.Future<void> deletePayment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePayment,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> togglePayment(
    String? memberId,
    String? committeeId,
    DateTime? date,
    String? hostId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #togglePayment,
          [
            memberId,
            committeeId,
            date,
            hostId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveJoinedCommittee(
    String? committeeCode,
    String? memberCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveJoinedCommittee,
          [
            committeeCode,
            memberCode,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<Map<dynamic, dynamic>> getJoinedCommittees() => (super.noSuchMethod(
        Invocation.method(
          #getJoinedCommittees,
          [],
        ),
        returnValue: <Map<dynamic, dynamic>>[],
      ) as List<Map<dynamic, dynamic>>);

  @override
  _i5.Future<void> removeJoinedCommittee(String? committeeCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeJoinedCommittee,
          [committeeCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setSelectedCycle(
    String? committeeId,
    int? cycle,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSelectedCycle,
          [
            committeeId,
            cycle,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getSelectedCycle(String? committeeId) => (super.noSuchMethod(
        Invocation.method(
          #getSelectedCycle,
          [committeeId],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<bool> isFirstLaunch() => (super.noSuchMethod(
        Invocation.method(
          #isFirstLaunch,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setFirstLaunchComplete() => (super.noSuchMethod(
        Invocation.method(
          #setFirstLaunchComplete,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isBiometricEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setBiometricEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setBiometricEnabled,
          [enabled],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getLanguage,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguage,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> setLanguage(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [languageCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i2.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isOnline() => (super.noSuchMethod(
        Invocation.method(
          #isOnline,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.SyncResult> syncAll(String? hostId) => (super.noSuchMethod(
        Invocation.method(
          #syncAll,
          [hostId],
        ),
        returnValue: _i5.Future<_i2.SyncResult>.value(_FakeSyncResult_0(
          this,
          Invocation.method(
            #syncAll,
            [hostId],
          ),
        )),
      ) as _i5.Future<_i2.SyncResult>);

  @override
  _i5.Future<_i2.SyncCounts> syncCommittees(String? hostId) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncCommittees,
          [hostId],
        ),
        returnValue: _i5.Future<_i2.SyncCounts>.value(_FakeSyncCounts_1(
          this,
          Invocation.method(
            #syncCommittees,
            [hostId],
          ),
        )),
      ) as _i5.Future<_i2.SyncCounts>);

  @override
  _i5.Future<_i2.SyncCounts> syncMembers(String? committeeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncMembers,
          [committeeId],
        ),
        returnValue: _i5.Future<_i2.SyncCounts>.value(_FakeSyncCounts_1(
          this,
          Invocation.method(
            #syncMembers,
            [committeeId],
          ),
        )),
      ) as _i5.Future<_i2.SyncCounts>);

  @override
  _i5.Future<_i2.SyncCounts> syncPayments(String? committeeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncPayments,
          [committeeId],
        ),
        returnValue: _i5.Future<_i2.SyncCounts>.value(_FakeSyncCounts_1(
          this,
          Invocation.method(
            #syncPayments,
            [committeeId],
          ),
        )),
      ) as _i5.Future<_i2.SyncCounts>);

  @override
  _i5.Future<bool> deleteCommitteeFromCloud(String? committeeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCommitteeFromCloud,
          [committeeId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteMemberFromCloud(String? memberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMemberFromCloud,
          [memberId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i7.Committee?> syncCommitteeByCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncCommitteeByCode,
          [code],
        ),
        returnValue: _i5.Future<_i7.Committee?>.value(),
      ) as _i5.Future<_i7.Committee?>);
}

/// A class which mocks [AutoSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAutoSyncService extends _i1.Mock implements _i11.AutoSyncService {
  MockAutoSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveCommittee(_i7.Committee? committee) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCommittee,
          [committee],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> deleteCommittee(
    String? committeeId,
    String? hostId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCommittee,
          [
            committeeId,
            hostId,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> archiveCommittee(_i7.Committee? committee) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveCommittee,
          [committee],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unarchiveCommittee(_i7.Committee? committee) =>
      (super.noSuchMethod(
        Invocation.method(
          #unarchiveCommittee,
          [committee],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveMember(_i8.Member? member) => (super.noSuchMethod(
        Invocation.method(
          #saveMember,
          [member],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteMember(
    String? memberId,
    String? committeeId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMember,
          [
            memberId,
            committeeId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateMemberPayoutOrder(
    String? memberId,
    int? order,
    String? committeeId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberPayoutOrder,
          [
            memberId,
            order,
            committeeId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> savePayment(_i9.Payment? payment) => (super.noSuchMethod(
        Invocation.method(
          #savePayment,
          [payment],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> togglePayment(
    String? memberId,
    String? committeeId,
    DateTime? date,
    String? hostId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #togglePayment,
          [
            memberId,
            committeeId,
            date,
            hostId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [RealtimeSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeSyncService extends _i1.Mock
    implements _i12.RealtimeSyncService {
  MockRealtimeSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onDataChanged(_i13.VoidCallback? _onDataChanged) => super.noSuchMethod(
        Invocation.setter(
          #onDataChanged,
          _onDataChanged,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markCommitteeForDelete(String? committeeId) => super.noSuchMethod(
        Invocation.method(
          #markCommitteeForDelete,
          [committeeId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markMemberForDelete(String? memberId) => super.noSuchMethod(
        Invocation.method(
          #markMemberForDelete,
          [memberId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markMemberForUpdate(String? memberId) => super.noSuchMethod(
        Invocation.method(
          #markMemberForUpdate,
          [memberId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void markPaymentForUpdate(String? paymentId) => super.noSuchMethod(
        Invocation.method(
          #markPaymentForUpdate,
          [paymentId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isPaymentPendingUpdate(String? paymentId) => (super.noSuchMethod(
        Invocation.method(
          #isPaymentPendingUpdate,
          [paymentId],
        ),
        returnValue: false,
      ) as bool);

  @override
  void startListening(String? hostId) => super.noSuchMethod(
        Invocation.method(
          #startListening,
          [hostId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopListening() => super.noSuchMethod(
        Invocation.method(
          #stopListening,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i3.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified => (super.noSuchMethod(
        Invocation.getter(#emailVerified),
        returnValue: false,
      ) as bool);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
      ) as bool);

  @override
  _i3.UserMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeUserMetadata_2(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i3.UserMetadata);

  @override
  List<_i3.UserInfo> get providerData => (super.noSuchMethod(
        Invocation.getter(#providerData),
        returnValue: <_i3.UserInfo>[],
      ) as List<_i3.UserInfo>);

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
      ) as String);

  @override
  _i3.MultiFactor get multiFactor => (super.noSuchMethod(
        Invocation.getter(#multiFactor),
        returnValue: _FakeMultiFactor_3(
          this,
          Invocation.getter(#multiFactor),
        ),
      ) as _i3.MultiFactor);

  @override
  _i5.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdToken,
          [forceRefresh],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i3.IdTokenResult> getIdTokenResult(
          [bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdTokenResult,
          [forceRefresh],
        ),
        returnValue: _i5.Future<_i3.IdTokenResult>.value(_FakeIdTokenResult_4(
          this,
          Invocation.method(
            #getIdTokenResult,
            [forceRefresh],
          ),
        )),
      ) as _i5.Future<_i3.IdTokenResult>);

  @override
  _i5.Future<_i3.UserCredential> linkWithCredential(
          _i3.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithCredential,
          [credential],
        ),
        returnValue: _i5.Future<_i3.UserCredential>.value(_FakeUserCredential_5(
          this,
          Invocation.method(
            #linkWithCredential,
            [credential],
          ),
        )),
      ) as _i5.Future<_i3.UserCredential>);

  @override
  _i5.Future<_i3.UserCredential> linkWithProvider(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithProvider,
          [provider],
        ),
        returnValue: _i5.Future<_i3.UserCredential>.value(_FakeUserCredential_5(
          this,
          Invocation.method(
            #linkWithProvider,
            [provider],
          ),
        )),
      ) as _i5.Future<_i3.UserCredential>);

  @override
  _i5.Future<_i3.UserCredential> reauthenticateWithProvider(
          _i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithProvider,
          [provider],
        ),
        returnValue: _i5.Future<_i3.UserCredential>.value(_FakeUserCredential_5(
          this,
          Invocation.method(
            #reauthenticateWithProvider,
            [provider],
          ),
        )),
      ) as _i5.Future<_i3.UserCredential>);

  @override
  _i5.Future<_i3.UserCredential> reauthenticateWithPopup(
          _i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithPopup,
          [provider],
        ),
        returnValue: _i5.Future<_i3.UserCredential>.value(_FakeUserCredential_5(
          this,
          Invocation.method(
            #reauthenticateWithPopup,
            [provider],
          ),
        )),
      ) as _i5.Future<_i3.UserCredential>);

  @override
  _i5.Future<void> reauthenticateWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithRedirect,
          [provider],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserCredential> linkWithPopup(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPopup,
          [provider],
        ),
        returnValue: _i5.Future<_i3.UserCredential>.value(_FakeUserCredential_5(
          this,
          Invocation.method(
            #linkWithPopup,
            [provider],
          ),
        )),
      ) as _i5.Future<_i3.UserCredential>);

  @override
  _i5.Future<void> linkWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithRedirect,
          [provider],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i3.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPhoneNumber,
          [
            phoneNumber,
            verifier,
          ],
        ),
        returnValue:
            _i5.Future<_i3.ConfirmationResult>.value(_FakeConfirmationResult_6(
          this,
          Invocation.method(
            #linkWithPhoneNumber,
            [
              phoneNumber,
              verifier,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ConfirmationResult>);

  @override
  _i5.Future<_i3.UserCredential> reauthenticateWithCredential(
          _i3.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithCredential,
          [credential],
        ),
        returnValue: _i5.Future<_i3.UserCredential>.value(_FakeUserCredential_5(
          this,
          Invocation.method(
            #reauthenticateWithCredential,
            [credential],
          ),
        )),
      ) as _i5.Future<_i3.UserCredential>);

  @override
  _i5.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendEmailVerification(
          [_i3.ActionCodeSettings? actionCodeSettings]) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [actionCodeSettings],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.User> unlink(String? providerId) => (super.noSuchMethod(
        Invocation.method(
          #unlink,
          [providerId],
        ),
        returnValue: _i5.Future<_i3.User>.value(_FakeUser_7(
          this,
          Invocation.method(
            #unlink,
            [providerId],
          ),
        )),
      ) as _i5.Future<_i3.User>);

  @override
  _i5.Future<void> updateEmail(String? newEmail) => (super.noSuchMethod(
        Invocation.method(
          #updateEmail,
          [newEmail],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updatePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updatePhoneNumber(
          _i3.PhoneAuthCredential? phoneCredential) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhoneNumber,
          [phoneCredential],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [displayName],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updatePhotoURL(String? photoURL) => (super.noSuchMethod(
        Invocation.method(
          #updatePhotoURL,
          [photoURL],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateProfile({
    String? displayName,
    String? photoURL,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoURL: photoURL,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i3.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyBeforeUpdateEmail,
          [
            newEmail,
            actionCodeSettings,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
