// Mocks generated by Mockito 5.4.5 from annotations
// in committee_app/test/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:committee_app/core/models/committee.dart' as _i4;
import 'package:committee_app/core/models/member.dart' as _i5;
import 'package:committee_app/core/models/payment.dart' as _i6;
import 'package:committee_app/services/database_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i2.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveCommittee(_i4.Committee? committee) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCommittee,
          [committee],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i4.Committee> getHostedCommittees(String? hostId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHostedCommittees,
          [hostId],
        ),
        returnValue: <_i4.Committee>[],
      ) as List<_i4.Committee>);

  @override
  _i4.Committee? getCommitteeById(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getCommitteeById,
        [id],
      )) as _i4.Committee?);

  @override
  _i4.Committee? getCommitteeByCode(String? code) =>
      (super.noSuchMethod(Invocation.method(
        #getCommitteeByCode,
        [code],
      )) as _i4.Committee?);

  @override
  _i3.Future<void> deleteCommittee(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCommittee,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveMember(_i5.Member? member) => (super.noSuchMethod(
        Invocation.method(
          #saveMember,
          [member],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i5.Member> getMembersByCommittee(String? committeeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMembersByCommittee,
          [committeeId],
        ),
        returnValue: <_i5.Member>[],
      ) as List<_i5.Member>);

  @override
  _i5.Member? getMemberById(String? id) =>
      (super.noSuchMethod(Invocation.method(
        #getMemberById,
        [id],
      )) as _i5.Member?);

  @override
  _i5.Member? getMemberByCode(
    String? committeeId,
    String? memberCode,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getMemberByCode,
        [
          committeeId,
          memberCode,
        ],
      )) as _i5.Member?);

  @override
  _i3.Future<void> deleteMember(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMember,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateMemberPayoutOrder(
    String? memberId,
    int? order,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberPayoutOrder,
          [
            memberId,
            order,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> savePayment(_i6.Payment? payment) => (super.noSuchMethod(
        Invocation.method(
          #savePayment,
          [payment],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i6.Payment> getPaymentsByCommittee(String? committeeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsByCommittee,
          [committeeId],
        ),
        returnValue: <_i6.Payment>[],
      ) as List<_i6.Payment>);

  @override
  List<_i6.Payment> getPaymentsByMember(String? memberId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentsByMember,
          [memberId],
        ),
        returnValue: <_i6.Payment>[],
      ) as List<_i6.Payment>);

  @override
  _i6.Payment? getPayment(
    String? memberId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getPayment,
        [
          memberId,
          date,
        ],
      )) as _i6.Payment?);

  @override
  _i3.Future<void> deletePayment(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePayment,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> togglePayment(
    String? memberId,
    String? committeeId,
    DateTime? date,
    String? hostId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #togglePayment,
          [
            memberId,
            committeeId,
            date,
            hostId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveJoinedCommittee(
    String? committeeCode,
    String? memberCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveJoinedCommittee,
          [
            committeeCode,
            memberCode,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<Map<dynamic, dynamic>> getJoinedCommittees() => (super.noSuchMethod(
        Invocation.method(
          #getJoinedCommittees,
          [],
        ),
        returnValue: <Map<dynamic, dynamic>>[],
      ) as List<Map<dynamic, dynamic>>);

  @override
  _i3.Future<void> removeJoinedCommittee(String? committeeCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeJoinedCommittee,
          [committeeCode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void setSelectedCycle(
    String? committeeId,
    int? cycle,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSelectedCycle,
          [
            committeeId,
            cycle,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getSelectedCycle(String? committeeId) => (super.noSuchMethod(
        Invocation.method(
          #getSelectedCycle,
          [committeeId],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<bool> isFirstLaunch() => (super.noSuchMethod(
        Invocation.method(
          #isFirstLaunch,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> setFirstLaunchComplete() => (super.noSuchMethod(
        Invocation.method(
          #setFirstLaunchComplete,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isBiometricEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> setBiometricEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setBiometricEnabled,
          [enabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> getLanguage() => (super.noSuchMethod(
        Invocation.method(
          #getLanguage,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguage,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> setLanguage(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [languageCode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
