// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANO9qmhToM_kfp85YLWZdmsPtt7n98ZNs',
    appId: '1:216531343276:web:48400f50b5f7960e490c09',
    messagingSenderId: '216531343276',
    projectId: 'commiteeapp-7cd16',
    authDomain: 'commiteeapp-7cd16.firebaseapp.com',
    storageBucket: 'commiteeapp-7cd16.firebasestorage.app',
    measurementId: 'G-2JH34PTCBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyuYVFnF-enUcSfOge_7M40EenOwQKFqQ',
    appId: '1:216531343276:android:4904ebd09b93956d490c09',
    messagingSenderId: '216531343276',
    projectId: 'commiteeapp-7cd16',
    storageBucket: 'commiteeapp-7cd16.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0FmFLCeYDiGPE6dNvAPUK-pEwMXBOY58',
    appId: '1:216531343276:ios:f93e66543b44de8c490c09',
    messagingSenderId: '216531343276',
    projectId: 'commiteeapp-7cd16',
    storageBucket: 'commiteeapp-7cd16.firebasestorage.app',
    iosBundleId: 'com.committee.committeeApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0FmFLCeYDiGPE6dNvAPUK-pEwMXBOY58',
    appId: '1:216531343276:ios:f93e66543b44de8c490c09',
    messagingSenderId: '216531343276',
    projectId: 'commiteeapp-7cd16',
    storageBucket: 'commiteeapp-7cd16.firebasestorage.app',
    iosBundleId: 'com.committee.committeeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANO9qmhToM_kfp85YLWZdmsPtt7n98ZNs',
    appId: '1:216531343276:web:50644caa8f32d173490c09',
    messagingSenderId: '216531343276',
    projectId: 'commiteeapp-7cd16',
    authDomain: 'commiteeapp-7cd16.firebaseapp.com',
    storageBucket: 'commiteeapp-7cd16.firebasestorage.app',
    measurementId: 'G-920YQ18LN4',
  );

}